[package]
name = "jump-hash"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5"  # For benchmarking
proptest = "1.3"   # For property-based testing
rand = "0.8"       # For generating random test data
